# Generated by Django 4.2.19 on 2025-03-05 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookingDate',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='isBooked',
            new_name='is_booked',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='seatNumber',
            new_name='seat_number',
        ),
    ]
