# Generated by Django 4.2.19 on 2025-03-05 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_bookingdate_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='releaseDate',
            new_name='release_date',
        ),
    ]
